### ISSUE TITLE
a suggestion about code writing more concise

### ISSUE THREAD

**Issue by liqianglog** [mroderick/PubSubJS#181] opened 2020-07-01 09:54 UTC
Now it's：
PubSub.subscribe(‘xxx’,(msg,data)=>{this.xxx(data)})
After position replacement：
PubSub.subscribe(‘xxx’,(data ,msg)=>{this.xxx(data)})
It can be abbreviated as：
PubSub.subscribe(‘xxx’,this.xxx)

I  have a high degree of simplicity in code. So in my opinion,  it can be more concise after adjustment here. I hope my suggestion can be adopted.

**Comment by mroderick** [comment] 2020-07-16 07:41
This is a duplicate of #180, that you opened four days earlier. If you have further comments, please post them in the original issue.

**Closed by mroderick** 2020-07-16 07:41 UTC
